AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation Template to allow your AWS Account(s) to access Kumolus
Parameters:
  RoleName:
    Description: Name of the Role to be created
    Type: String
    Default: Kumolus-CrossAcctRole
Resources:
  KumolusCrossAcctRole:
    Type: 'AWS::IAM::Role'
    Description: Cross Account Role for Kumolus Application Access
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::702574401249:root'
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: Kumolus-InventoryRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: SSMMandatory
                Effect: Allow
                Action:
                  - ssm:ListInstanceAssociations
                  - ssm:ListResourceDataSync
                  - ssm:ListDocuments
                  - ssm:ListInventoryEntries
                  - ssm:ListDocumentVersions
                  - ssm:ListAssociations
                Resource: "*"
              - Sid: ConfigMandatory
                Effect: Allow
                Action:
                  - config:Describe*
                  - config:DescribeConfigRules
                  - config:GetComplianceDetailsByConfigRule
                  - config:DescribeConfigurationRecorders
                  - config:DescribeConfigurationRecorderStatus
                  - config:DescribeDeliveryChannels
                Resource: "*"
              - Sid: SNSMandatory
                Effect: Allow
                Action:
                  - sns:ListTopics
                  - sns:GetTopicAttributes
                  - sns:ListSubscriptionsByTopic
                  - sns:GetTopicAttributes
                  - sns:GetSubscriptionAttributes
                Resource: "*"
              - Sid: SQSMandatory
                Effect: Allow
                Action:
                  - sqs:ListQueues
                  - sqs:GetQueueAttributes
                Resource: "*"
              - Sid: KinesisMandatory
                Effect: Allow
                Action:
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListStreams
                Resource: "*"
              - Sid: LambdaMandatory
                Effect: Allow
                Action:
                  - lambda:ListFunctions
                  - lambda:ListTags
                Resource: "*"
              - Sid: StoragegatewayMandatory
                Effect: Allow
                Action:
                  - storagegateway:List*
                  - storagegateway:Describe*
                Resource: "*"
              - Sid: SESMandatory
                Effect: Allow
                Action:
                  - ses:GetIdentityDkimAttributes
                  - ses:GetIdentityVerificationAttributes
                  - ses:GetSendQuota
                  - ses:ListIdentities
                  - ses:GetSendStatistics
                Resource: "*"
              - Sid: DynamoDBMandatory
                Effect: Allow
                Action:
                  - dynamodb:ListTables
                  - dynamodb:DescribeTable
                  - dynamodb:ListTagsOfResource
                Resource: "*"
              - Sid: CloudFormationMandatory
                Effect: Allow
                Action:
                  - cloudformation:ListStackResources
                  - cloudformation:GetStackPolicy
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                Resource: "*"
              - Sid: CloudFrontMandatory
                Effect: Allow
                Action:
                  - cloudfront:GetDistributionConfig
                  - cloudfront:GetStreamingDistributionConfig
                  - cloudfront:List*
                Resource: "*"
              - Sid: CognitoMandatory
                Effect: Allow
                Action:
                  - cognito-idp:ListUsers
                  - cognito-idp:ListGroups
                  - cognito-idp:ListIdentityProviders
                  - cognito-idp:ListUsersInGroup
                  - cognito-idp:ListUserPools
                  - cognito-identity:ListIdentityPools
                  - cognito-identity:ListIdentities
                Resource: "*"
              - Sid: CloudHSMMandatory
                Effect: Allow
                Action:
                  - cloudhsm:List*
                  - cloudhsm:Describe*
                Resource: "*"
              - Sid: DataPipelineMandatory
                Effect: Allow
                Action:
                  - datapipeline:ListPipelines
                  - datapipeline:DescribePipelines
                  - datapipeline:GetPipelineDefinition
                Resource: "*"
              - Sid: DirectConnectMandatory
                Effect: Allow
                Action:
                  - directconnect:DescribeConnections
                  - directconnect:DescribeVirtualInterfaces
                  - directconnect:DescribeLocations
                Resource: "*"
              - Sid: ElasticFileSystemMandatory
                Effect: Allow
                Action:
                  - elasticfilesystem:DescribeTags
                  - elasticfilesystem:DescribeFileSystems
                Resource: "*"
              - Sid: Route53Mandatory
                Effect: Allow
                Action:
                  - route53:ListHostedZones
                  - route53:ListHealthChecks
                  - route53:ListResourceRecordSets
                Resource: "*"
              - Sid: WorkspacesMandatory
                Effect: Allow
                Action:
                  - workspaces:DescribeWorkspaceDirectories
                  - workspaces:DescribeWorkspaceBundles
                  - workspaces:DescribeWorkspaces
                Resource: "*"
              - Sid: ACMMandatory
                Effect: Allow
                Action:
                  - acm:DescribeCertificate
                  - acm:ListCertificates
                  - acm:GetCertificate
                Resource: "*"
              - Sid: GlacierMandatory
                Effect: Allow
                Action:
                  - glacier:ListVaults
                  - glacier:DescribeVault
                  - glacier:DescribeJob
                  - glacier:ListTagsForVault
                  - glacier:GetVaultNotifications
                  - glacier:ListJobs
                  - glacier:GetJobOutput
                Resource: "*"
              - Sid: ElasticMapReduceMandatory
                Effect: Allow
                Action:
                  - elasticmapreduce:List*
                  - elasticmapreduce:Describe*
                Resource: "*"
              - Sid: ESMandatory
                Effect: Allow
                Action:
                  - es:ListDomainNames
                  - es:DescribeElasticsearchDomains
                Resource: "*"
              - Sid: SDBMandatory
                Effect: Allow
                Action:
                  - sdb:ListDomains
                  - sdb:DomainMetadata
                Resource: "*"
              - Sid: elasticacheMandatory
                Effect: Allow
                Action:
                  - elasticache:List*
                  - elasticache:Describe*
                Resource: "*"
              - Sid: SWFMandatory
                Effect: Allow
                Action:
                  - swf:ListWorkflowTypes
                  - swf:ListActivityTypes
                  - swf:ListDomains
                  - swf:ListClosedWorkflowExecutions
                Resource: "*"
              - Sid: OtherMandatory
                Effect: Allow
                Action:
                  - iot:ListThings
                  - iot:DescribeThing
                  - cloudsearch:Describe*
                  - support:*
                Resource: "*"

              - Sid: EC2Mandatory
                Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeVolumes
                  - ec2:DescribeVolumesModifications
                  - ec2:DescribeSnapshots
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeRouteTables
                  - ec2:DescribeSnapshotAttribute
                  - ec2:DescribeReservedInstances
                  - ec2:DescribeSubnets
                  - ec2:DescribeAddresses
                  - ec2:DescribeInstanceAttribute
                  - ec2:DescribeVpcs
                  - ec2:DescribeVpcAttribute
                  - ec2:DescribeInstanceStatus
                  - ec2:DescribeIamInstanceProfileAssociations
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeImages
                  - ec2:DescribeVolumeAttribute
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeAvailabilityZones
                  - ec2:GetConsoleOutput
                  - ec2:DescribeTags
                  - ec2:AssociateRouteTable
                Resource: "*"
              - Sid: RDSMandatory
                Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                  - rds:DescribeDBSubnetGroups
                  - rds:DescribeDBSnapshots
                  - rds:DescribeDBSecurityGroups
                  - rds:ListTagsForResource
                  - rds:DescribeDBParameterGroups
                  - rds:DescribeDBParameters
                Resource: "*"
              - Sid: ELBMandatory
                Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancerPolicies
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeInstanceHealth
                  - elasticloadbalancing:DescribeTags
                Resource: "*"
              - Sid: AutoScalingMandatory
                Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeLoadBalancers
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:DescribePolicies
                  - autoscaling:DescribeTags
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeLoadBalancerTargetGroups
                  - autoscaling:DescribeTerminationPolicyTypes
                Resource: "*"
              - Sid: S3Mandatory
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLogging
                  - s3:GetBucketLocation
                  - s3:GetBucketWebsite
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketPolicy
                Resource: "*"
              - Sid: CloudtrailMandatory
                Effect: Allow
                Action:
                  - cloudtrail:ListTrails
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrail
                  - cloudtrail:LookupEvents
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:GetEventSelectors
                  - cloudtrail:GetInsightSelectors
                Resource: "*"
              - Sid: CloudWatchMandatory
                Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DescribeAlarmsForMetric
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource: "*"
              - Sid: KMSMandatory
                Effect: Allow
                Action:
                  - kms:ListKeys
                  - kms:DescribeKey
                  - kms:ListAliases
                  - kms:GetKeyRotationStatus
                  - kms:GetKeyPolicy
                  - kms:ListKeyPolicies
                  - kms:ListGrants
                  - kms:ListResourceTags
                Resource: "*"
              - Sid: IAMMandatory
                Effect: Allow
                Action:
                  - iam:ListUsers
                  - iam:GetUser
                  - iam:ListInstanceProfiles
                  - iam:ListServerCertificates
                  - iam:GenerateCredentialReport
                  - iam:GetCredentialReport
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:GetPolicy
                  - iam:ListUserPolicies
                  - iam:ListAttachedUserPolicies
                  - iam:ListAttachedRolePolicies
                  - iam:ListAttachedGroupPolicies
                  - iam:ListRolePolicies
                  - iam:ListRoles
                  - iam:ListGroupPolicies
                  - iam:ListGroups
                  - iam:ListMFADevices
                  - iam:GetLoginProfile
                  - iam:ListSSHPublicKeys
                  - iam:ListAccessKeys
                  - iam:GetGroup
                  - iam:GetAccountPasswordPolicy
                  - organizations:DescribeOrganization
                Resource: "*"
              - Sid: ECSMandatory
                Effect: Allow
                Action:
                  - ecs:ListClusters
                  - ecs:ListServices
                  - ecs:ListTasks
                  - ecs:ListTaskDefinitions
                  - ecs:ListContainerInstances
                  - ecs:DescribeTaskDefinition
                  - ecs:DescribeTasks
                  - ecs:DescribeClusters
                  - ecs:DescribeServices
                  - ecs:DescribeContainerInstances
                  - ecs:ListTagsForResource
                Resource: "*"
Outputs:
  KumolusRoleARN:
    Description: Role ARN for Kumolus Adapter Configuration
    Value: !GetAtt 
      - KumolusCrossAcctRole
      - Arn
