AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A cloudformation template that allow your AWS account's (parent/payer) access to Kumolus
Parameters:
  RoleName:
    Description: Name of the Role to be created
    Type: String
    Default: Kumolus-CrossAcctRole
Resources:
  KumolusCrossAcctRole:
    Type: 'AWS::IAM::Role'
    Description: Cross Account Role for Kumolus Application Access (Payer Account)
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::702574401249:root'
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: Kumolus-CUR-RW
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cur:DescribeReportDefinitions
                  - cur:PutReportDefinition
                  - cur:ModifyReportDefinition
                  - cur:DeleteReportDefinition
                  - s3:GetBucketACL
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:GetBucketPolicy
                  - s3:GetBucketTagging
                  - s3:GetBucketWebsite
                  - s3:GetBucketNotification
                  - s3:GetLifecycleConfiguration
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetObject
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:DeleteBucketPolicy
                  - s3:PutBucketCORS
                  - s3:PutBucketLogging
                  - s3:PutBucketNotification
                  - s3:PutBucketVersioning
                  - s3:PutBucketTagging
                  - s3:PutBucketPolicy
                  - s3:PutBucketAcl
                  - s3:PutEncryptionConfiguration
                  - Organizations:ListRoots
                  - Organizations:ListAccounts
                  - Organizations:ListParents
                  - Organizations:ListChildren
                  - Organizations:ListAccountsForParent
                  - Organizations:ListOrganizationalUnitsForParent
                  - Organizations:ListPolicies
                  - Organizations:ListPoliciesForTarget
                  - Organizations:ListCreateAccountStatus
                  - Organizations:ListTagsForResource
                  - Organizations:DescribeAccount
                  - Organizations:DescribeOrganization
                  - Organizations:DescribePolicy
                  - Organizations:DescribeOrganizationalUnit
                  - ec2:DescribeVpcs
                  - ce:GetReservationPurchaseRecommendation
                  - ce:GetReservationCoverage
                  - ce:GetSavingsPlansUtilizationDetails
                  - ce:GetSavingsPlansPurchaseRecommendation
                  - ce:GetSavingsPlansUtilization
                  - ec2:DescribeReservedInstances
                  - rds:DescribeReservedDBInstances
                  - redshift:DescribeReservedNodes
                  - elasticache:DescribeReservedCacheNodes
                  - es:DescribeReservedElasticsearchInstances
                Resource: '*'
Outputs:
  KumolusRoleARN:
    Description: Role ARN for Kumolus Adapter Configuration
    Value: !GetAtt 
      - KumolusCrossAcctRole
      - Arn
